### ISSUE TITLE
[BUG] Optimize local cache of *.wasm files

### ISSUE THREAD

**Issue by cipchk** [openimsdk/openim-sdk-js-wasm#116]
### OpenIM Server Version

3.8

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

`3.8` 增加了 `openIM.wasm` 本地缓存，的确解决加载缓慢问题。但是是通过 `etag` 与 `last-modified` 来判断是否需要更新，但这种方式一但重写发布新 Docker Image 时文件的修改时间会发生改变，但实际上我们 `wasm` 几乎很少会变化，这种变化是打包工具的原因。

建议在缓存逻辑上可以增加一个以 URL Path 作为 Key 就好的选项。

**Comment by Bloomingg** [comment]
I don't quite understand what this does, and the URL doesn't seem to change.
