### ISSUE TITLE
[BUG] wasm_exec.js overwritten the native window.close method

### ISSUE THREAD

**Issue by OrrinHatch** [openimsdk/openim-sdk-js-wasm#123]
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

don't use the native window.close

**Comment by OrrinHatch** [comment]
temporary solution: `<script>var nativeClose = window.close;</script>`

**Comment by Bloomingg** [comment]
Because the calls between wasm and js are all registered on the window method.
