### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by xieshaoji01** [openimsdk/openim-sdk-js-wasm#149]
### OpenIM Server Version

3.5.3

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

在解除了好友关系后，然后在发送好友申请，接收方有收到好友申请同意的状态变化，但是发送方没有收到发送的状态变化，只有在浏览器无痕模式下才能获取到发送方的好友申请状态变化。

**Comment by Bloomingg** [comment]
you can update the sdk and server to the latest version and try again.

**Comment by xieshaoji01** [comment]
> you can update the sdk and server to the latest version and try again.

server版本是v3.5 做了很多业务，升级有比较大的问题。请问这个问题能否在3.5版本的sdk 做个修复。

**Comment by Bloomingg** [comment]
Due to limited team resources, currently only version `v3.8` is supported and maintained. Moreover, version `3.8` has fixed a large number of issues and been optimized. It is more recommended to upgrade and use it.

**Comment by xieshaoji01** [comment]
> you can update the sdk and server to the latest version and try again.
主要是后端服务牵扯太多开发和业务，如果调整后端可能会有非常大的工作量调整。
