### ISSUE TITLE
[BUG] WebSocket is not open. Message not sent.(env: macOS,mp,1.06.2210310; lib: 3.7.1)

### ISSUE THREAD

**Issue by 15975019972** [openimsdk/openim-sdk-js-wasm#151]
### OpenIM Server Version

3.7.1

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

WebSocket is not open. Message not sent.(env: macOS,mp,1.06.2210310; lib: 3.7.1)
![image](https://github.com/user-attachments/assets/247b075b-2252-4209-b8b0-205f9318139b)
基于react tarojs可以使用这个包开发微信小程序吗，好像都是问题报错

### Screenshots Link

111

**Comment by 15975019972** [comment]
import { Component, PropsWithChildren, useState } from 'react'
import { View, Text } from '@tarojs/components'
import { getSDK, CbEvents, CallbackEvent } from '@openim/client-sdk';
import './index.scss'

const IMSDK = getSDK()
export default class Index extends Component<PropsWithChildren> {

  componentWillMount () { }

  componentDidMount () {

    IMSDK.on(CbEvents.OnConnecting, handleConnecting);
    IMSDK.on(CbEvents.OnConnectFailed, handleConnectFailed);
    IMSDK.on(CbEvents.OnConnectSuccess, handleConnectSuccess);

    IMSDK.login({
      userID: '3893196195',
      token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiIzODkzMTk2MTk1IiwiUGxhdGZvcm1JRCI6NSwiZXhwIjoxNzQyMTg0NDg1LCJuYmYiOjE3MzQ0MDgxODUsImlhdCI6MTczNDQwODQ4NX0.U02C9Ic9FJP2V56TxyKHp6M4QoiAo9jM5JXRvO4aLC4',
      platformID: 5,
      wsAddr: 'xxx',
      apiAddr: 'xxx',
    });

    function handleConnecting() {
      console.log('hello')
      // Connecting...
    }

    function handleConnectFailed({ errCode, errMsg }: CallbackEvent) {
      // Connection failed ❌
      console.log(errCode, errMsg);
    }

    function handleConnectSuccess() {
      console.log('hello')
      // Connection successful ✅
    }
  }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  async sendMsg () {
    console.log('getSDK', getSDK);
    const message = (await IMSDK.createTextMessage('hello openim')).data;

    IMSDK.sendMessage({
      recvID: '9069085873',
      groupID: '',
      message,
    })
      .then(() => {
        // Message sent successfully ✉️
        console.log('msg success')
      })
      .catch(err => {
        // Failed to send message ❌
        console.log(err);
      });
  }

  render () {
    return (
      <View className='index'>
        <Text onClick={this.sendMsg}>Hello world!</Text>
      </View>
    )
  }
}
``

**Comment by 15975019972** [comment]
```
import { Component, PropsWithChildren, useState } from 'react'
import { View, Text } from '@tarojs/components'
import { getSDK, CbEvents, CallbackEvent } from '@openim/client-sdk';
import './index.scss'

const IMSDK = getSDK()
export default class Index extends Component<PropsWithChildren> {

  componentWillMount () { }

  componentDidMount () {

    IMSDK.on(CbEvents.OnConnecting, handleConnecting);
    IMSDK.on(CbEvents.OnConnectFailed, handleConnectFailed);
    IMSDK.on(CbEvents.OnConnectSuccess, handleConnectSuccess);

    IMSDK.login({
      userID: '3893196195',
      token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiIzODkzMTk2MTk1IiwiUGxhdGZvcm1JRCI6NSwiZXhwIjoxNzQyMTg0NDg1LCJuYmYiOjE3MzQ0MDgxODUsImlhdCI6MTczNDQwODQ4NX0.U02C9Ic9FJP2V56TxyKHp6M4QoiAo9jM5JXRvO4aLC4',
      platformID: 5,
      wsAddr: 'xxx',
      apiAddr: 'xxx',
    });

    function handleConnecting() {
      console.log('hello')
      // Connecting...
    }

    function handleConnectFailed({ errCode, errMsg }: CallbackEvent) {
      // Connection failed ❌
      console.log(errCode, errMsg);
    }

    function handleConnectSuccess() {
      console.log('hello')
      // Connection successful ✅
    }
  }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  async sendMsg () {
    console.log('getSDK', getSDK);
    const message = (await IMSDK.createTextMessage('hello openim')).data;

    IMSDK.sendMessage({
      recvID: '9069085873',
      groupID: '',
      message,
    })
      .then(() => {
        // Message sent successfully ✉️
        console.log('msg success')
      })
      .catch(err => {
        // Failed to send message ❌
        console.log(err);
      });
  }

  render () {
    return (
      <View className='index'>
        <Text onClick={this.sendMsg}>Hello world!</Text>
      </View>
    )
  }
}

```

**Comment by Bloomingg** [comment]
There is no log of login operations seen in the log you provided. Instead, login starts only after your send fails. You need to ensure that you have successfully logged in and received the callback of onConnectSuccess before sending a message.

**Comment by 15975019972** [comment]
![image](https://github.com/user-attachments/assets/e72154dd-8d23-4095-8f91-32ac6d23c6e3)
已经触发了onConnectSuccess回调 但还是有报错信息

**Comment by 15975019972** [comment]
需要我上传代码给你测试找原因吗

**Comment by Bloomingg** [comment]
I just noticed that your server version is 3.7.1? This SDK only supports server versions above 3.8.2.

**Comment by 15975019972** [comment]
https://github.com/15975019972/tarojsImdemo.git 你试试demo，小程序

**Comment by Bloomingg** [comment]
Is it normal after upgrading to 3.8.2?
