### ISSUE TITLE
[BUG] After setting changeGroupMemberMute successfully, group member information is not updated after the mute period ends, and the onGroupMemberInfoChanged interface is not triggered.

### ISSUE THREAD

**Issue by wo3330102** [openimsdk/openim-sdk-js-wasm#154]
### OpenIM Server Version

3.8.2

### Operating System and CPU Architecture

Windows (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

管理员在群组中通过changeGroupMemberMute接口设置成员禁言，该成员禁言时间结束后没有同步更新信息，
![image](https://github.com/user-attachments/assets/f89dcc70-a998-4739-859a-7a465b643eee)

通过getGroupMemberList接口获取的muteEndTime时长在当前时间之前，
![image](https://github.com/user-attachments/assets/43d16596-3ff1-43ac-8533-40eb8e8d01b2)

并且onGroupMemberInfoChanged接口也并未被触发

### Screenshots Link

![image](https://github.com/user-attachments/assets/43d16596-3ff1-43ac-8533-40eb8e8d01b2)

**Comment by Bloomingg** [comment]
After it ends, it will not trigger changes in group members. You can determine whether the mute has ended by checking whether muteEndTime is greater than the current time.
