### ISSUE TITLE
Is the npm library @openim/client-sdk compiled by this repository?

### ISSUE THREAD

**Issue by zsjinwei** [openimsdk/openim-sdk-js-wasm#155]
### What would you like to share?

@openim/client-sdk 这个npm库是这个仓库编译的吗? 是否可以分享编译方法, 或者提供@openim/client-sdk的源码, 需要这个库进行二次开发, 谢谢

**Comment by Bloomingg** [comment]
The source code of @openim/client-sdk is currently a commercial version. If needed, you can contact the official business.
