### ISSUE TITLE
[BUG] errCode 10006

### ISSUE THREAD

**Issue by zhuyuzhu** [openimsdk/openim-sdk-js-wasm#158]
### OpenIM Server Version

3.8.2

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

**Issue Title:** Error when calling SendMessage: "Cannot assign to read only property 'latestMsgSendTime' of object '#<Object>'"

**Description:**

I encountered an error when attempting to call the `SendMessage` function. The detailed error message is as follows:

```
Error: MiniProgramError
{"event":"SendMessage","operationID":"k8caf2jssk1735571299641","data":null,"errMsg":"Cannot assign to read only property 'latestMsgSendTime' of object '#<Object>'","errCode":10006}
```

It seems that the property `latestMsgSendTime` is read-only and cannot be modified. 

**Steps to Reproduce:**
1. Call the `SendMessage` function.
2. Observe the error message.

**Expected Behavior:**
The `SendMessage` function should execute successfully without attempting to modify a read-only property.

**Actual Behavior:**
The function throws an error indicating that it cannot assign to the read-only property `latestMsgSendTime`.

**Additional Information:**
- Operation ID: k8caf2jssk1735571299641

Please look into this issue and provide guidance on how to resolve it. Thank you!

### Screenshots Link

![image](https://github.com/user-attachments/assets/5330381e-0590-415a-9f97-6b830c67b77f)

**Comment by zhuyuzhu** [comment]
Additional Information:

Operation ID: k8caf2jssk1735571299641
SDK used: '@openim/client-sdk', specifier: 0.0.11-alpha.1, version: 0.0.11-alpha.1
Additional Context:

When using WeChat Developer Tools for debugging, sending messages was working fine a few days ago, but now it fails with the error mentioned above.
When debugging on a real device, sending messages works, but receiving messages results in the same error.
Please look into this issue and provide guidance on how to resolve it. Thank you!

**Comment by zhuyuzhu** [comment]
![image](https://github.com/user-attachments/assets/0b6c6682-175a-49d2-a80b-03af07b25c8b)

**Comment by zhuyuzhu** [comment]
![image](https://github.com/user-attachments/assets/720b8664-a3bb-418e-b59b-65c3a69eba2e)

**Comment by zhuyuzhu** [comment]
When a new message is received, the following error message is displayed:

![image](https://github.com/user-attachments/assets/3e0fa023-5998-423d-8b3b-9224f5507903)

**Comment by Bloomingg** [comment]
Confirm, is your server version 3.8.0? The jssdk requires the server version to be above 3.8.2.

**Comment by zhuyuzhu** [comment]
> 确认一下，你的服务器版本是3.8.0吗？jssdk要求服务器版本在3.8.2以上。

"Yes, our server version is 3.8.2. However, in my WeChat Mini Program, I am using '@openim/client-sdk' with the specifier 0.0.11-alpha.1 and the version 0.0.11-alpha.1."

![image](https://github.com/user-attachments/assets/d7f8711e-b799-4a9c-8608-d52a9b31a20e)

**Comment by zhuyuzhu** [comment]
> Confirm, is your server version 3.8.0? The jssdk requires the server version to be above 3.8.2.

# Docker images
MONGO_IMAGE=mongo:7.0                      # MongoDB server image version
REDIS_IMAGE=redis:7.0.0                    # Redis server image version
KAFKA_IMAGE=bitnami/kafka:3.5.1            # Kafka server image version
MINIO_IMAGE=minio/minio:RELEASE.2024-01-11T07-46-16Z  # MinIO server image version
PROMETHEUS_IMAGE=prom/prometheus:v2.51.2   # Prometheus monitoring system image version
ALERTMANAGER_IMAGE=prom/alertmanager:v0.27.0 # Alertmanager for Prometheus image version
GRAFANA_IMAGE=grafana/grafana:11.0.1       # Grafana visualization tool image version
ETCD_IMAGE=quay.io/coreos/etcd:v3.5.13

OPENIM_WEB_FRONT_IMAGE=openim/openim-web-front:release-v3.8.1
OPENIM_ADMIN_FRONT_IMAGE=openim/openim-admin-front:release-v1.8.3

NODE_EXPORTER_IMAGE=prom/node-exporter:v1.7.0 # Prometheus Node Exporter image version

# OpenIM server and chat service images
OPENIM_SERVER_IMAGE=openim/openim-server:release-v3.8.2 # OpenIM server application image versi
on
#OPENIM_SERVER_IMAGE=registry.cn-hangzhou.aliyuncs.com/openimsdk/openim-server:release-v3.8.1

OPENIM_CHAT_IMAGE=openim/openim-chat:v1.8.2 # OpenIM chat application image version
#OPENIM_CHAT_IMAGE=registry.cn-hangzhou.aliyuncs.com/openimsdk/openim-chat:release-v1.8.2

**Comment by Bloomingg** [comment]
how about your IDE version? No one has had the same question like this before this.

**Comment by zhuyuzhu** [comment]
"I have wrapped an additional layer on top of the IM SDK myself, which caused this issue."
